Test #19

diff --git a/.github/workflows/prepare_release.yml b/.github/workflows/prepare_release.yml
--- a/.github/workflows/prepare_release.yml
+++ b/.github/workflows/prepare_release.yml
@@ -16,6 +16,13 @@ jobs:
       - name: Checkout current branch
         uses: actions/checkout@v3
 
+      - name: Fail if release branch already exists
+        run: |
+          if git ls-remote --exit-code --heads origin release/${{ inputs.version }}; then
+            echo "Release branch release/${{ inputs.version }} already exists. Failing."
+            exit 1
+          fi
+
       - name: Create and push release branch
         run: |
           git fetch origin
@@ -40,6 +47,7 @@ jobs:
           git push origin HEAD   
 
       - name: Call build and deploy script
+      # ToDo: fail script if it fails
         run: |
           echo "Building and deploying WebSDK..."
           # Call your build and deploy script here
diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,20 +11,13 @@ jobs:
   CheckVersion:
     runs-on: ubuntu-latest
     steps:
-
-      # Check that a release branch med den angivna versionen finns
-      - name: Check if release branch exists
-        id: check_branch
+      - name: Fail if release branch does not exist
         run: |
-          git fetch origin
-          if git show-ref --verify --quiet refs/heads/release/${{ inputs.version }}; then
-            echo "Release branch release/${{ inputs.version }} exists."
-            echo "::set-output name=branch_exists::true"
-          else
-            echo "Release branch release/${{ inputs.version }} does not exist."
-            echo "::set-output name=branch_exists::false"
+          if ! git ls-remote --exit-code --heads origin release/${{ inputs.version }}; then
+            echo "Release branch release/${{ inputs.version }} does not exist. Failing."
+            exit 1
           fi
-  
+
   FinilizeRelase:
     runs-on: ubuntu-latest
     needs: CheckVersion
