Test #27

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,17 +21,15 @@ jobs:
             exit 1
           fi
 
-      # ToDo, kolla oxå om det finns en tag med den versionen, avbryt om det gör det
-      #  - ändra oxå längre ner
-      #- name: Check if tag already exists
-      #  run: |
-      #    TAG_NAME=${{ inputs.version }}
-      #    if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
-      #      echo "Tag $TAG_NAME already exists. Failing."
-      #      exit 1
-      #    fi  
+      - name: Check if tag already exists
+        run: |
+          TAG_NAME=${{ inputs.version }}
+          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
+            echo "Tag $TAG_NAME already exists. Failing."
+            exit 1
+          fi  
 
-  FinalizeRelease:
+  CreateAandUploadReleaseAssets:
     runs-on: ubuntu-latest
     needs: CheckReleaseBranchExists
     permissions:
@@ -50,13 +48,9 @@ jobs:
       - name: Create tag if it does not exist
         run: |
           TAG_NAME=${{ inputs.version }}
-          if git rev-parse "refs/tags/$TAG_NAME" >/dev/null 2>&1; then
-            echo "Tag $TAG_NAME already exists."
-          else
-            git tag --annotate "$TAG_NAME" --message "Release $TAG_NAME"
-            git push --tags
-            echo "Tag $TAG_NAME created and pushed."
-          fi      
+          git tag --annotate "$TAG_NAME" --message "Release $TAG_NAME"
+          git push --tags
+          echo "Tag $TAG_NAME created and pushed."
       
       - name: Zip and upload binaries
         run: |
@@ -72,15 +66,7 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y google-chrome-stable
 
-        # wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
-        # sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
-        # sudo apt-get update
-        # sudo apt-get install -y google-chrome-stable
-
-      - name: List releaseFiles directory
-        run: ls -l ./docs/release_notes
-
-      - name: Print HTML to PDF
+      - name: Convert release notes from html to pdf
         run: |
           google-chrome --headless --no-sandbox --disable-gpu --print-to-pdf=./docs/release_notes/ACE_Web_SDK_Release_Notes.pdf ./docs/release_notes/ACE_Web_SDK_Release_Notes.html
 
@@ -119,6 +105,23 @@ jobs:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: ./binaries/${{ steps.find_websdk_zip.outputs.websdk_zip_file }}
           asset_name: ${{ steps.find_websdk_zip.outputs.websdk_zip_file }}
+          asset_content_type: application/zip
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Find the Web SDK debug zip file
+        id: find_websdk_debug_zip
+        run: |
+          ZIP_FILE=$(find ./binaries -type f -name "ACEWebSDK-${{ inputs.version }}-debug-*.zip" | head -n 1)
+          echo "websdk_debug_zip_file=$(basename "$ZIP_FILE")" >> $GITHUB_OUTPUT
+
+      - name: Upload zip file to release
+        if: steps.find_websdk_debug_zip.outputs.websdk_debug_zip_file != ''
+        uses: actions/upload-release-asset@v1.0.2
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: ./binaries/${{ steps.find_websdk_debug_zip.outputs.websdk_debug_zip_file }}
+          asset_name: ${{ steps.find_websdk_debug_zip.outputs.websdk_debug_zip_file }}
           asset_content_type: application/zip
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
